#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later WITH cantil-additional-permissions
"""
Generate xx_vector.h: a deterministic Noise_XX_25519_ChaChaPoly_SHA256 trace
from fixed, easy-to-eyeball initiator/responder static + ephemeral keypairs,
plus the first two post-handshake transport ciphertexts.  Consumed by the
firmware/tests/noise_session ztest suite as its primary regression vector.

The spec implementation lives in noise_xx_ref.py; gen_cacophony_vector.py
validates that implementation against the published Cacophony reference
vectors.  See that script for the keystone correctness check.
"""

import os
import sys

from noise_xx_ref import run_xx, c_array


def main():
    v = run_xx(
        iS_priv=bytes.fromhex("11" * 32),
        iE_priv=bytes.fromhex("22" * 32),
        rS_priv=bytes.fromhex("33" * 32),
        rE_priv=bytes.fromhex("44" * 32),
        prologue=b"",
        handshake_payloads=(b"", b"", b""),
        transport_messages=[
            ("i", b"hello from initiator"),
            ("r", b"hello from responder"),
        ],
    )

    msg_a_pt = v["transport"][0][1]
    msg_a_ct = v["transport"][0][2]
    msg_b_pt = v["transport"][1][1]
    msg_b_ct = v["transport"][1][2]

    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(__file__), "src", "xx_vector.h",
    )

    parts = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later WITH cantil-additional-permissions */",
        "/* GENERATED by firmware/tests/noise_session/gen_xx_vector.py — do not edit. */",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/* Noise_XX_25519_ChaChaPoly_SHA256 — deterministic trace from fixed keys.",
        " * Initiator and responder static + ephemeral private keys are constants;",
        " * the script derives the resulting wire bytes and post-handshake transport",
        " * ciphertexts.  Empty prologue, empty handshake-message payloads — matches",
        " * session.c's wire format. */",
        "",
    ]
    fields = [
        ("XX_IS_PRIV", v["iS_priv"]), ("XX_IS_PUB", v["iS_pub"]),
        ("XX_IE_PRIV", v["iE_priv"]), ("XX_IE_PUB", v["iE_pub"]),
        ("XX_RS_PRIV", v["rS_priv"]), ("XX_RS_PUB", v["rS_pub"]),
        ("XX_RE_PRIV", v["rE_priv"]), ("XX_RE_PUB", v["rE_pub"]),
        ("XX_MSG1", v["msg1"]), ("XX_MSG2", v["msg2"]), ("XX_MSG3", v["msg3"]),
        ("XX_HANDSHAKE_HASH", v["handshake_hash"]),
        ("XX_INITIATOR_TX_KEY", v["initiator_tx_key"]),
        ("XX_RESPONDER_TX_KEY", v["responder_tx_key"]),
        ("XX_MSG_A_PT", msg_a_pt), ("XX_MSG_A_CT", msg_a_ct),
        ("XX_MSG_B_PT", msg_b_pt), ("XX_MSG_B_CT", msg_b_ct),
    ]
    for name, data in fields:
        parts.append(c_array(name, data))
        parts.append("")

    with open(out, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
