/* AUTO-GENERATED by scripts/gen_names_data.py — do not edit by hand.
 * Source: names.txt
 * Encoding: raw UTF-8 bytes, separator=0xFF (invalid UTF-8, safe delimiter).
 * Format: <name-bytes> 0xFF <name-bytes> 0xFF ...
 */

#pragma once
#include <stdint.h>

/* Total number of names in the dataset. */
#define NAMES_COUNT 1918U

/* Maximum number of names returnable in a single GET_RANDOM_NAMES response. */
#define NAMES_BATCH_MAX 64U

/* Flat UTF-8 name data.  Each name is followed by 0xFF. */
extern const uint8_t  names_data[13049];

/* Byte offset of the first byte of each name within names_data[]. */
extern const uint16_t names_byte_offsets[NAMES_COUNT];

/* Byte length of each name (UTF-8 bytes, separator not included). */
extern const uint8_t  names_byte_lengths[NAMES_COUNT];
