#!/usr/bin/env python3
"""
Generate C source + header for the baby names dataset from a plain text file
(one name per line, UTF-8).  Used by the firmware build process.

Encoding
--------
    Names stored as raw UTF-8 bytes (as-is from the text file).
    Separator: 0xFF — an invalid UTF-8 byte, safe unambiguous delimiter for
    any language or script.

    Format: <name-utf8-bytes> 0xFF <name-utf8-bytes> 0xFF ...
    The last name is also followed by 0xFF.

Output
------
    <out_base>.h  —  declarations
    <out_base>.c  —  definitions (names_data[], names_byte_offsets[],
                                  names_byte_lengths[])

Usage
-----
    python3 scripts/gen_names_data.py \\
        contrib/names.txt \\
        firmware/src/names/names_data
"""

import argparse
import os
import sys


SEPARATOR = 0xFF  # Invalid UTF-8 byte; safe unambiguous name delimiter


HEADER_TMPL = """\
/* AUTO-GENERATED by scripts/gen_names_data.py — do not edit by hand.
 * Source: {source}
 * Encoding: raw UTF-8 bytes, separator=0xFF (invalid UTF-8, safe delimiter).
 * Format: <name-bytes> 0xFF <name-bytes> 0xFF ...
 */

#pragma once
#include <stdint.h>

/* Total number of names in the dataset. */
#define NAMES_COUNT {count}U

/* Maximum number of names returnable in a single GET_RANDOM_NAMES response. */
#define NAMES_BATCH_MAX 64U

/* Flat UTF-8 name data.  Each name is followed by 0xFF. */
extern const uint8_t  names_data[{data_len}];

/* Byte offset of the first byte of each name within names_data[]. */
extern const uint16_t names_byte_offsets[NAMES_COUNT];

/* Byte length of each name (UTF-8 bytes, separator not included). */
extern const uint8_t  names_byte_lengths[NAMES_COUNT];
"""

SOURCE_TMPL = """\
/* AUTO-GENERATED by scripts/gen_names_data.py — do not edit by hand. */

#include "names_data.h"

const uint8_t names_data[{data_len}] = {{
{data_hex}
}};

const uint16_t names_byte_offsets[NAMES_COUNT] = {{
{offsets}
}};

const uint8_t names_byte_lengths[NAMES_COUNT] = {{
{lengths}
}};
"""


def hex_dump(data: bytearray, cols: int = 16) -> str:
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def uint16_dump(values: list[int], cols: int = 8) -> str:
    lines = []
    for i in range(0, len(values), cols):
        chunk = values[i:i + cols]
        lines.append("    " + ", ".join(f"{v}U" for v in chunk) + ",")
    return "\n".join(lines)


def uint8_dump(values: list[int], cols: int = 16) -> str:
    lines = []
    for i in range(0, len(values), cols):
        chunk = values[i:i + cols]
        lines.append("    " + ", ".join(str(v) for v in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("names_txt", help="Path to names text file (one name per line)")
    ap.add_argument("out_base",  help="Output base path (without extension)")
    args = ap.parse_args()

    with open(args.names_txt, encoding="utf-8") as f:
        names = [line.strip() for line in f if line.strip()]

    if not names:
        sys.exit(f"ERROR: No names found in {args.names_txt}")

    # Build flat byte stream
    flat: bytearray = bytearray()
    byte_offsets: list[int] = []
    byte_lengths: list[int] = []

    for name in names:
        encoded = name.encode("utf-8")
        if SEPARATOR in encoded:
            sys.exit(f"ERROR: name {name!r} contains 0xFF — cannot use as separator.")
        byte_offsets.append(len(flat))
        byte_lengths.append(len(encoded))
        flat.extend(encoded)
        flat.append(SEPARATOR)

    # Sanity checks
    if max(byte_offsets) > 0xFFFF:
        sys.exit(f"ERROR: byte offset exceeds uint16_t range — too many/long names.")
    if max(byte_lengths) > 255:
        sys.exit(f"ERROR: a name exceeds 255 bytes — exceeds uint8_t length field.")

    os.makedirs(os.path.dirname(args.out_base) or ".", exist_ok=True)

    source_label = os.path.basename(args.names_txt)
    header = HEADER_TMPL.format(
        source=source_label,
        count=len(names),
        data_len=len(flat),
    )
    source = SOURCE_TMPL.format(
        data_len=len(flat),
        data_hex=hex_dump(flat),
        offsets=uint16_dump(byte_offsets),
        lengths=uint8_dump(byte_lengths),
    )

    with open(args.out_base + ".h", "w") as f:
        f.write(header)
    with open(args.out_base + ".c", "w") as f:
        f.write(source)

    print(f"{len(names)} names, {len(flat)} bytes → "
          f"{args.out_base}.{{h,c}}")


if __name__ == "__main__":
    main()
