#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later WITH cantil-additional-permissions
#
# Generate known-answer test vectors for the noise_crypto_mbedtls.c primitives.
# Run: python3 gen_vectors.py > src/vectors.h
#
# X25519 + SHA-256 KATs are RFC-standard literals.
# ChaCha20-Poly1305 + HKDF-2 reference values are computed here against the
# Python cryptography library so divergence in the mbedtls path is caught.

import sys
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives import hashes, hmac


def c_bytes(name, data):
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{ {body} }};"


def noise_nonce(n):
    return b"\x00\x00\x00\x00" + n.to_bytes(8, "little")


def noise_hkdf2(ck, ikm):
    h = hmac.HMAC(ck, hashes.SHA256())
    h.update(ikm)
    temp_key = h.finalize()

    h1 = hmac.HMAC(temp_key, hashes.SHA256())
    h1.update(b"\x01")
    t1 = h1.finalize()

    h2 = hmac.HMAC(temp_key, hashes.SHA256())
    h2.update(t1 + b"\x02")
    t2 = h2.finalize()
    return t1, t2


def main():
    out = sys.stdout

    out.write("/* SPDX-License-Identifier: GPL-3.0-or-later WITH cantil-additional-permissions */\n")
    out.write("/* GENERATED by gen_vectors.py — do not edit by hand. */\n")
    out.write("#pragma once\n\n#include <stdint.h>\n#include <stddef.h>\n\n")

    # ── X25519 (RFC 7748 §6.1) ─────────────────────────────────────────
    alice_priv = bytes.fromhex(
        "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
    alice_pub = bytes.fromhex(
        "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")
    bob_priv = bytes.fromhex(
        "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
    bob_pub = bytes.fromhex(
        "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f")
    shared = bytes.fromhex(
        "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742")

    out.write("/* X25519 — RFC 7748 §6.1 */\n")
    out.write(c_bytes("X25519_ALICE_PRIV", alice_priv) + "\n")
    out.write(c_bytes("X25519_ALICE_PUB",  alice_pub)  + "\n")
    out.write(c_bytes("X25519_BOB_PRIV",   bob_priv)   + "\n")
    out.write(c_bytes("X25519_BOB_PUB",    bob_pub)    + "\n")
    out.write(c_bytes("X25519_SHARED",     shared)     + "\n\n")

    # ── SHA-256 ("abc") — FIPS 180-2 ───────────────────────────────────
    sha_abc = bytes.fromhex(
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    out.write("/* SHA-256(\"abc\") — FIPS 180-2 */\n")
    out.write(c_bytes("SHA256_ABC_A", b"a") + "\n")
    out.write(c_bytes("SHA256_ABC_BC", b"bc") + "\n")
    out.write(c_bytes("SHA256_ABC_HASH", sha_abc) + "\n\n")

    # ── ChaCha20-Poly1305 with Noise nonce encoding ────────────────────
    # Vector 1: n=0
    key1 = bytes.fromhex(
        "1c9240a5eb55d38af333888604f6b5f0473917c1402b80099dca5cbc207075c0")
    ad1 = b"\xf3\x33\x88\x86"
    pt1 = b"Internet-Drafts are draft documents valid for a maximum of six months"
    ct1 = ChaCha20Poly1305(key1).encrypt(noise_nonce(0), pt1, ad1)

    # Vector 2: n=1 (nonce-encoding probe — same key/pt/ad as v1, should differ)
    ct2 = ChaCha20Poly1305(key1).encrypt(noise_nonce(1), pt1, ad1)

    # Vector 3: empty plaintext, empty ad (Noise handshake uses this often)
    key3 = bytes(32)
    pt3 = b""
    ad3 = b""
    ct3 = ChaCha20Poly1305(key3).encrypt(noise_nonce(0), pt3, ad3)

    out.write("/* ChaCha20-Poly1305 with Noise nonce (4 zero bytes || uint64 LE) */\n")
    out.write(c_bytes("AEAD_KEY1",  key1) + "\n")
    out.write(c_bytes("AEAD_AD1",   ad1)  + "\n")
    out.write(c_bytes("AEAD_PT1",   pt1)  + "\n")
    out.write(c_bytes("AEAD_CT1_N0", ct1) + "\n")
    out.write(c_bytes("AEAD_CT1_N1", ct2) + "\n")
    out.write(c_bytes("AEAD_KEY3_ZERO", key3) + "\n")
    out.write(c_bytes("AEAD_CT3_EMPTY", ct3) + "\n\n")

    # ── HKDF-2 (Noise's HKDF function) ─────────────────────────────────
    # ck = SHA-256("Noise_XX_25519_ChaChaPoly_SHA256" || "test salt")
    # ikm = "test input keying material"
    ck = bytes.fromhex(
        "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b")
    ikm = b"input keying material"
    t1, t2 = noise_hkdf2(ck, ikm)

    out.write("/* Noise HKDF-2: HKDF-SHA-256(salt=ck, ikm), 64-byte output split */\n")
    out.write(c_bytes("HKDF_CK",   ck)   + "\n")
    out.write(c_bytes("HKDF_IKM",  ikm)  + "\n")
    out.write(c_bytes("HKDF_OUT1", t1)   + "\n")
    out.write(c_bytes("HKDF_OUT2", t2)   + "\n\n")

    # ── HKDF-2 with empty ikm (used by Noise Split()) ──────────────────
    t1e, t2e = noise_hkdf2(ck, b"")
    out.write("/* Noise HKDF-2 with empty ikm — used by Split() */\n")
    out.write(c_bytes("HKDF_OUT1_EMPTY", t1e) + "\n")
    out.write(c_bytes("HKDF_OUT2_EMPTY", t2e) + "\n")


if __name__ == "__main__":
    main()
